apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-fixit-nodeport
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: {{ .Values.container.port }}
    targetPort: {{ .Values.container.port }}
    nodePort: {{ .Values.node.port }}
  selector:
    app: {{ .Release.Name }}-fixit
